name: Backport on pull_request[closed]
on:
  pull_request:
    types: [closed]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    # Only run for case 1 (checked by label)
    # Don't run on closed unmerged pull requests
    if: >
      contains(github.event.pull_request.labels.*.name, 'backport case1-backport-target')
      && github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v3
      - name: Backport
        uses: zeebe-io/backport-action@korthout-optimal-fetch-depth
        with:
          # Required
          # Token to authenticate requests to GitHub
          github_token: ${{ secrets.BACKPORT_ACTION_TOKEN }}

          # Required
          # Working directory for the backport action
          github_workspace: ${{ github.workspace }}
