name: Backport on issue_comment[created]
on:
  issue_comment:
    types: [created]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    # Only run on comment containing `/backport`
    if: >
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/backport')
    steps:
      - uses: actions/checkout@v3
      - name: Backport
        id: backport
        uses: korthout/backport-action@revert-376-revert-375-skipMergeCommits
        with:
          # copy_labels_pattern: .+
          merge_commits: skip
          target_branches: case4-target-branches
      - name: Print was_successful output
        run: echo "${{ steps.backport.outputs.was_successful }}"
      - name: Print was_successful_by_target output
        run: echo "${{ steps.backport.outputs.was_successful_by_target }}"
