name: Backport on issue_comment[created]
on:
  issue_comment:
    types: [created]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    # Only run on comment containing `/backport`
    if: >
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/backport')
    steps:
      - uses: actions/checkout@v3
      - name: Backport
        id: backport
        uses: korthout/backport-action@main