name: Test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: test/case1.sh
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_EVENTS_TOKEN }}
